{"name": "test_add[nagetives]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -3 == 3\n  +-3\n  -3", "trace": "self = <testcases.test_cacu_yaml.TestCalc object at 0x000002230D866348>, setprint = None, fristofall = None, a = -1, b = -2, expect = 3\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expect', datas['add']['datas'], ids=datas['add']['ids'])\n    def test_add(self, setprint, fristofall, a, b, expect):\n        # calc = Calculator()\n        result = self.calc.add(a, b)\n>       assert result == expect\nE       assert -3 == 3\nE         +-3\nE         -3\n\ntest_cacu_yaml.py:26: AssertionError"}, "parameters": [{"name": "a", "value": "-1"}, {"name": "b", "value": "-2"}, {"name": "expect", "value": "3"}], "start": 1604643590038, "stop": 1604643590038, "uuid": "f0031b3a-b496-4f58-af09-8cc9e8699d23", "historyId": "2985e304795ba2740ef193f8e60e3a75", "testCaseId": "ad0130f34bd17b13bbe8d80f846f309c", "fullName": "test_cacu_yaml.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_cacu_yaml"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-FCPOG81"}, {"name": "thread", "value": "14904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cacu_yaml"}]}