{"name": "test_add[floats]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1.2 == 1\n  +1.2\n  -1", "trace": "self = <testcases.test_cacu_yaml.TestCalc object at 0x000002230D881F88>, setprint = None, fristofall = None, a = 0.5, b = 0.7, expect = 1\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expect', datas['add']['datas'], ids=datas['add']['ids'])\n    def test_add(self, setprint, fristofall, a, b, expect):\n        # calc = Calculator()\n        result = self.calc.add(a, b)\n>       assert result == expect\nE       assert 1.2 == 1\nE         +1.2\nE         -1\n\ntest_cacu_yaml.py:26: AssertionError"}, "parameters": [{"name": "a", "value": "0.5"}, {"name": "b", "value": "0.7"}, {"name": "expect", "value": "1"}], "start": 1604643590054, "stop": 1604643590054, "uuid": "4e02d151-123f-4253-8d09-5e8244b92027", "historyId": "d9ecb6b7b501a79888b6bca3e29d4c05", "testCaseId": "ad0130f34bd17b13bbe8d80f846f309c", "fullName": "test_cacu_yaml.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_cacu_yaml"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-FCPOG81"}, {"name": "thread", "value": "14904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cacu_yaml"}]}